import { FamilySearchType } from "./FamilySearchType";

export const tes: FamilySearchType = {
  graph: {
    "11": "M7NM-3VB",
    "12": "M9WP-FX4",
    "13": "KDQ8-TWV",
    "14": "LYK6-VQ2",
    "15": "LB1S-5V6",
    "2": "LB5W-MSC",
    "3": "LB6L-Z6K",
    "4": "LB57-YKT",
    "5": "LCM6-WCL",
    "2.1": "L51K-TWP",
    "6": "LBXV-7R4",
    "2.2": "L8WB-9SV",
    "7": "KDQ8-MZ1",
    "2.3": "MJ8F-VH3",
    "8": "LB5T-GL5",
    "2.4": "9SMP-MGG",
    "9": "K8RT-425",
    "2.5": "GMJ9-NZL",
    "2.6": "GF37-JCJ",
    "2.1a": "GCGG-LWF",
    "2.2a": "94K9-WZ4",
    "2.3a": "9791-Z88",
    "10": "GWCK-WC2",
    "2.5a": "GS2P-DFD",
  },
  persons: {
    "LB5T-GL5": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "LB5T-GL5",
      inPrivateSpace: false,
      lifespan: "1328–1360",
      living: false,
      memoryCount: 0,
      name: "Roger de Mortimer",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Roger de Mortimer",
          nameForms: [
            {
              familyPart: "de Mortimer",
              fullText: "Roger de Mortimer",
              givenPart: "Roger",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: null,
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 14,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "M2SJ-XMF", preferred: false }],
    },
    "KDQ8-TWV": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "KDQ8-TWV",
      inPrivateSpace: false,
      lifespan: "1328–1385",
      living: false,
      memoryCount: 0,
      name: "Joan of Kent",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Joan of Kent",
          nameForms: [
            {
              familyPart: "of Kent",
              fullText: "Joan of Kent",
              givenPart: "Joan",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: null,
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 8,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MY89-BGJ", preferred: false }],
      suggestions: {
        dataQualityList: [
          {
            category: "DATA_QUALITY",
            contextId: null,
            entityId: "KDQ8-TWV",
            type: {
              canBeDismissed: false,
              category: "DATA_QUALITY",
              context: "PERSON",
              name: "MISSING_BURIAL_PLACE_STANDARD",
            },
          },
        ],
        empty: false,
        researchSuggestionList: null,
      },
    },
    "L8WB-9SV": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 7,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "L8WB-9SV",
      inPrivateSpace: false,
      lifespan: "1385–1415",
      living: false,
      memoryCount: 0,
      name: "Richard of Conisburgh 3rd Earl of Cambridge",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Richard of Conisburgh 3rd Earl of Cambridge",
          nameForms: [
            {
              familyPart: null,
              fullText: "Richard of Conisburgh 3rd Earl of Cambridge",
              givenPart: "Richard of Conisburgh",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "3rd Earl of Cambridge",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 11,
      spaceId: "MMMM-MMM",
    },
    "9791-Z88": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 1,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "9791-Z88",
      inPrivateSpace: false,
      lifespan: "1403–1432",
      living: false,
      memoryCount: 0,
      name: "Anne Stafford",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Anne Stafford",
          nameForms: [
            {
              familyPart: "Stafford",
              fullText: "Anne Stafford",
              givenPart: "Anne",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: null,
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 2,
      spaceId: "MMMM-MMM",
    },
    "M7NM-3VB": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 2,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "M7NM-3VB",
      inPrivateSpace: false,
      lifespan: "1332–1363",
      living: false,
      memoryCount: 0,
      name: "Elizabeth de Burgh Duchess of Clarence",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Elizabeth de Burgh Duchess of Clarence",
          nameForms: [
            {
              familyPart: "Burgh",
              fullText: "Elizabeth de Burgh Duchess of Clarence",
              givenPart: "Elizabeth de",
              lang: "und",
              prefixPart: null,
              script: "UNSPECIFIED",
              suffixPart: "Duchess of Clarence",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 16,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "M5C9-BF6", preferred: false }],
    },
    "M9WP-FX4": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "M9WP-FX4",
      inPrivateSpace: false,
      lifespan: "1314–1360",
      living: false,
      memoryCount: 0,
      name: "Thomas Holland 1st Earl of Kent",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Thomas Holland 1st Earl of Kent",
          nameForms: [
            {
              familyPart: "Holland",
              fullText: "Thomas Holland 1st Earl of Kent",
              givenPart: "Thomas",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "1st Earl of Kent",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 4,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MY89-BGJ", preferred: false }],
    },
    "LYK6-VQ2": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 2,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "LYK6-VQ2",
      inPrivateSpace: false,
      lifespan: "1306–1376",
      living: false,
      memoryCount: 0,
      name: "Richard FitzAlan",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Richard FitzAlan",
          nameForms: [
            {
              familyPart: "FitzAlan",
              fullText: "Richard FitzAlan",
              givenPart: "Richard",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: null,
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 13,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MYY4-9SD", preferred: false }],
    },
    "GF37-JCJ": {
      collaborateCount: 0,
      deleted: false,
      descendant: true,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: false,
      id: "GF37-JCJ",
      inPrivateSpace: false,
      lifespan: "1397–Deceased",
      living: false,
      memoryCount: 0,
      name: "Alice de Mortimer",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Alice de Mortimer",
          nameForms: [
            {
              familyPart: "de Mortimer",
              fullText: "Alice de Mortimer",
              givenPart: "Alice",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: null,
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 0,
      spaceId: "MMMM-MMM",
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "GF37-JCJ",
            type: {
              canBeDismissed: false,
              category: "RESEARCH_SUGGESTION",
              context: "PERSON",
              name: "NO_SOURCES_ATTACHED",
            },
          },
        ],
      },
    },
    "LB5W-MSC": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "LB5W-MSC",
      inPrivateSpace: false,
      lifespan: "1374–1398",
      living: false,
      memoryCount: 0,
      name: "Roger Mortimer 4th Earl of March",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Roger Mortimer 4th Earl of March",
          nameForms: [
            {
              familyPart: "Mortimer",
              fullText: "Roger Mortimer 4th Earl of March",
              givenPart: "Roger",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "4th Earl of March",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 9,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MT3J-1RT", preferred: false }],
    },
    "GWCK-WC2": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "GWCK-WC2",
      inPrivateSpace: false,
      lifespan: "1338–1368",
      living: false,
      memoryCount: 0,
      name: "Lionel of Antwerp 1st Duke of Clarence",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Lionel of Antwerp 1st Duke of Clarence",
          nameForms: [
            {
              familyPart: "of Antwerp",
              fullText: "Lionel of Antwerp 1st Duke of Clarence",
              givenPart: "Lionel",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "1st Duke of Clarence",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 22,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "M5C9-BF6", preferred: false }],
    },
    "K8RT-425": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "K8RT-425",
      inPrivateSpace: false,
      lifespan: "1332–1381",
      living: false,
      memoryCount: 0,
      name: "Lady Philippa de Montagu Countess of March",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Lady Philippa de Montagu Countess of March",
          nameForms: [
            {
              familyPart: "de Montagu",
              fullText: "Lady Philippa de Montagu Countess of March",
              givenPart: "Philippa",
              lang: "en",
              prefixPart: "Lady",
              script: "ENGLISH",
              suffixPart: "Countess of March",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 9,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "M2SJ-XMF", preferred: false }],
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "K8RT-425",
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "PERSON",
              name: "PERSON_MAY_HAVE_ANOTHER_SPOUSE",
            },
          },
        ],
      },
    },
    "LB57-YKT": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "LB57-YKT",
      inPrivateSpace: false,
      lifespan: "1352–1381",
      living: false,
      memoryCount: 0,
      name: "Edmund de Mortimer 3rd Earl of March",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Edmund de Mortimer 3rd Earl of March",
          nameForms: [
            {
              familyPart: "de Mortimer",
              fullText: "Edmund de Mortimer 3rd Earl of March",
              givenPart: "Edmund",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "3rd Earl of March",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 30,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MYGH-SMM", preferred: false }],
    },
    "LBXV-7R4": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "LBXV-7R4",
      inPrivateSpace: false,
      lifespan: "1350–1397",
      living: false,
      memoryCount: 0,
      name: "Thomas Holland 2nd Earl of Kent",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Thomas Holland 2nd Earl of Kent",
          nameForms: [
            {
              familyPart: "Holland",
              fullText: "Thomas Holland 2nd Earl of Kent",
              givenPart: "Thomas",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "2nd Earl of Kent",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 8,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MRTL-DFJ", preferred: false }],
    },
    "LB6L-Z6K": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "LB6L-Z6K",
      inPrivateSpace: false,
      lifespan: "1373–1405",
      living: false,
      memoryCount: 0,
      name: "Alianore Holland Countess of March",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Alianore Holland Countess of March",
          nameForms: [
            {
              familyPart: "Holland",
              fullText: "Alianore Holland Countess of March",
              givenPart: "Alianore",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "Countess of March",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 6,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MT3J-1RT", preferred: false }],
    },
    "GCGG-LWF": {
      collaborateCount: 0,
      deleted: false,
      descendant: true,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "GCGG-LWF",
      inPrivateSpace: false,
      lifespan: "1387–1423",
      living: false,
      memoryCount: 0,
      name: "Eleanor de Mortimer",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Eleanor de Mortimer",
          nameForms: [
            {
              familyPart: "de Mortimer",
              fullText: "Eleanor de Mortimer",
              givenPart: "Eleanor",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: null,
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 0,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MBV9-3LC", preferred: false }],
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "GCGG-LWF",
            type: {
              canBeDismissed: false,
              category: "RESEARCH_SUGGESTION",
              context: "PERSON",
              name: "NO_SOURCES_ATTACHED",
            },
          },
        ],
      },
    },
    "KDQ8-MZ1": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "KDQ8-MZ1",
      inPrivateSpace: false,
      lifespan: "1351–1416",
      living: false,
      memoryCount: 0,
      name: "Lady Alice FitzAlan Countess of Kent",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Lady Alice FitzAlan Countess of Kent",
          nameForms: [
            {
              familyPart: "FitzAlan",
              fullText: "Lady Alice FitzAlan Countess of Kent",
              givenPart: "Alice",
              lang: "en",
              prefixPart: "Lady",
              script: "ENGLISH",
              suffixPart: "Countess of Kent",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 4,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MRTL-DFJ", preferred: false }],
    },
    "L51K-TWP": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 1,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "L51K-TWP",
      inPrivateSpace: false,
      lifespan: "1388–1428",
      living: false,
      memoryCount: 0,
      name: "Thomas Montagu 4th Earl of Salisbury",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Thomas Montagu 4th Earl of Salisbury",
          nameForms: [
            {
              familyPart: "Montagu",
              fullText: "Thomas Montagu 4th Earl of Salisbury",
              givenPart: "Thomas",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "4th Earl of Salisbury",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 18,
      spaceId: "MMMM-MMM",
    },
    "94K9-WZ4": {
      collaborateCount: 0,
      deleted: false,
      descendant: true,
      discussionCount: 1,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "94K9-WZ4",
      inPrivateSpace: false,
      lifespan: "1388–1411",
      living: false,
      memoryCount: 0,
      name: "Anne de Mortimer Countess of Cambridge",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Anne de Mortimer Countess of Cambridge",
          nameForms: [
            {
              familyPart: "de Mortimer",
              fullText: "Anne de Mortimer Countess of Cambridge",
              givenPart: "Anne",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "Countess of Cambridge",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 13,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MTWC-ZYV", preferred: false }],
    },
    "9SMP-MGG": {
      collaborateCount: 0,
      deleted: false,
      descendant: true,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: false,
      id: "9SMP-MGG",
      inPrivateSpace: false,
      lifespan: "1393–1413",
      living: false,
      memoryCount: 0,
      name: "Roger Mortimer",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Roger Mortimer",
          nameForms: [
            {
              familyPart: "Mortimer",
              fullText: "Roger Mortimer",
              givenPart: "Roger",
              lang: "und",
              prefixPart: null,
              script: "UNSPECIFIED",
              suffixPart: null,
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 9,
      spaceId: "MMMM-MMM",
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "9SMP-MGG",
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "PERSON",
              name: "PERSON_MAY_HAVE_CHILDREN",
            },
          },
        ],
      },
    },
    "LB1S-5V6": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: true,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "LB1S-5V6",
      inPrivateSpace: false,
      lifespan: "1318–1372",
      living: false,
      memoryCount: 0,
      name: "Eleanor of Lancaster",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Eleanor of Lancaster",
          nameForms: [
            {
              familyPart: null,
              fullText: "Eleanor of Lancaster",
              givenPart: "Eleanor",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "of Lancaster",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 8,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MYY4-9SD", preferred: false }],
    },
    "MJ8F-VH3": {
      collaborateCount: 0,
      deleted: false,
      descendant: true,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: false,
      id: "MJ8F-VH3",
      inPrivateSpace: false,
      lifespan: "1391–1425",
      living: false,
      memoryCount: 0,
      name: "Edmund Mortimer 5th Earl of March",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Edmund Mortimer 5th Earl of March",
          nameForms: [
            {
              familyPart: "Mortimer",
              fullText: "Edmund Mortimer 5th Earl of March",
              givenPart: "Edmund",
              lang: "und",
              prefixPart: null,
              script: "UNSPECIFIED",
              suffixPart: "5th Earl of March",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 10,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MGQL-BPC", preferred: false }],
    },
    "GS2P-DFD": {
      collaborateCount: 0,
      deleted: false,
      descendant: true,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: true,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "GS2P-DFD",
      inPrivateSpace: false,
      lifespan: "1393–1434",
      living: false,
      memoryCount: 0,
      name: "Amery Averia Mortimer",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Amery Averia Mortimer",
          nameForms: [
            {
              familyPart: "Mortimer",
              fullText: "Amery Averia Mortimer",
              givenPart: "Amery Averia",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: null,
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 0,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MP79-TLP", preferred: false }],
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "GS2P-DFD",
            type: {
              canBeDismissed: false,
              category: "RESEARCH_SUGGESTION",
              context: "PERSON",
              name: "NO_SOURCES_ATTACHED",
            },
          },
        ],
      },
    },
    "GMJ9-NZL": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "MALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "GMJ9-NZL",
      inPrivateSpace: false,
      lifespan: "1390–1444",
      living: false,
      memoryCount: 0,
      name: "William Wroth II",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "William Wroth II",
          nameForms: [
            {
              familyPart: "Wroth",
              fullText: "William Wroth II",
              givenPart: "William",
              lang: "und",
              prefixPart: null,
              script: "UNSPECIFIED",
              suffixPart: "II",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 0,
      spaceId: "MMMM-MMM",
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "GMJ9-NZL",
            type: {
              canBeDismissed: false,
              category: "RESEARCH_SUGGESTION",
              context: "PERSON",
              name: "NO_SOURCES_ATTACHED",
            },
          },
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "GMJ9-NZL",
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "PERSON",
              name: "PERSON_MAY_HAVE_ANOTHER_SPOUSE",
            },
          },
        ],
      },
    },
    "LCM6-WCL": {
      collaborateCount: 0,
      deleted: false,
      descendant: false,
      discussionCount: 0,
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      gender: "FEMALE",
      hasMultipleFamiliesAsChild: false,
      hasMultipleFamiliesAsParent: false,
      hasRecordHints: false,
      hasSpouseOrChildren: true,
      id: "LCM6-WCL",
      inPrivateSpace: false,
      lifespan: "1355–1382",
      living: false,
      memoryCount: 0,
      name: "Philippa Plantagenet 5th Countess of Ulster",
      nameConclusion: {
        contributor: null,
        details: {
          detailsType: "NameDetails",
          fullText: "Philippa Plantagenet 5th Countess of Ulster",
          nameForms: [
            {
              familyPart: "Plantagenet",
              fullText: "Philippa Plantagenet 5th Countess of Ulster",
              givenPart: "Philippa",
              lang: "en",
              prefixPart: null,
              script: "ENGLISH",
              suffixPart: "5th Countess of Ulster",
            },
          ],
          nameType: "",
          preferredName: true,
          sourceCount: 0,
          style: "EUROTYPIC",
        },
        id: null,
        justification: "",
        multiValued: false,
        type: "NAME",
      },
      noteCount: 0,
      principlePerson: false,
      readOnly: false,
      size: "CUSTOM_NON_CACHEABLE",
      skeleton: false,
      sourceCount: 12,
      spaceId: "MMMM-MMM",
      spouses: [{ hasChildren: false, id: "MYGH-SMM", preferred: false }],
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "LCM6-WCL",
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "PERSON",
              name: "PERSON_MAY_HAVE_ANOTHER_SPOUSE",
            },
          },
        ],
      },
    },
  },
  relationships: {
    "MP79-TLP": {
      coupleId: "GMJ9-NZL~GS2P-DFD",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "+1415",
            julianDateRange: { earliestDay: 2237878, latestDay: 2237878 },
            localizedText: "1415",
            modifier: null,
            normalizedText: "1415",
            originalText: "1415",
          },
          deceasedFlag: null,
          description: null,
          place: {
            geoCode: { latitude: 51.6524, longitude: -0.0806 },
            id: 10619887,
            localizedText: "Enfield, Middlesex, England",
            normalizedText: "Enfield, Middlesex, England",
            originalText: "Enfield, Middlesex, England",
          },
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "MP79-TLP",
      preferred: false,
    },
    "MT3J-1RT": {
      coupleId: "LB5W-MSC~LB6L-Z6K",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "MT3J-1RT",
            id: null,
            justification: null,
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "COUPLE",
              name: "POSSIBLE_CHILD_GAP_AT_END",
            },
          },
        ],
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "+1388-10-07",
            julianDateRange: { earliestDay: 2228297, latestDay: 2228297 },
            localizedText: "7 October 1388",
            modifier: null,
            normalizedText: "7 October 1388",
            originalText: "7 October 1388",
          },
          deceasedFlag: null,
          description: null,
          place: null,
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "MT3J-1RT",
      preferred: false,
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "MT3J-1RT",
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "COUPLE",
              name: "POSSIBLE_CHILD_GAP_IN_MIDDLE",
            },
          },
        ],
      },
    },
    "M5C9-BF6": {
      coupleId: "GWCK-WC2~M7NM-3VB",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "M5C9-BF6",
            id: null,
            justification: null,
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "COUPLE",
              name: "POSSIBLE_CHILD_GAP_AT_END",
            },
          },
        ],
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "+1352-08-15",
            julianDateRange: { earliestDay: 2215095, latestDay: 2215095 },
            localizedText: "15 August 1352",
            modifier: null,
            normalizedText: "15 August 1352",
            originalText: "15 August 1352",
          },
          deceasedFlag: null,
          description: null,
          place: {
            geoCode: { latitude: 51.50782, longitude: -0.07503 },
            id: 10621575,
            localizedText: "Tower of London, Middlesex, England",
            normalizedText: "Tower of London, Middlesex, England",
            originalText: "Tower of London, Middlesex, England",
          },
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "M5C9-BF6",
      preferred: false,
    },
    "MYY4-9SD": {
      coupleId: "LYK6-VQ2~LB1S-5V6",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "+1345-04-05",
            julianDateRange: { earliestDay: 2212406, latestDay: 2212406 },
            localizedText: "5 April 1345",
            modifier: null,
            normalizedText: "5 April 1345",
            originalText: "5 April 1345",
          },
          deceasedFlag: null,
          description: null,
          place: {
            geoCode: { latitude: 52.4983, longitude: -2.5772 },
            id: 10598833,
            localizedText: "Ditton Priors, Shropshire, England",
            normalizedText: "Ditton Priors, Shropshire, England",
            originalText: "Ditton Priors, Shropshire, England",
          },
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "MYY4-9SD",
      preferred: false,
    },
    "MY89-BGJ": {
      coupleId: "M9WP-FX4~KDQ8-TWV",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "+1340",
            julianDateRange: { earliestDay: 2210485, latestDay: 2210485 },
            localizedText: "1340",
            modifier: null,
            normalizedText: "1340",
            originalText: "1340",
          },
          deceasedFlag: null,
          description: null,
          place: {
            geoCode: { latitude: 51.22608, longitude: 0.75054 },
            id: 10560312,
            localizedText: "Kent, England",
            normalizedText: "Kent, England",
            originalText: "Kent, England",
          },
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "MY89-BGJ",
      preferred: false,
    },
    "MBV9-3LC": {
      coupleId: "L51K-TWP~GCGG-LWF",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      hasChildren: true,
      id: "MBV9-3LC",
      preferred: false,
    },
    "MYGH-SMM": {
      coupleId: "LB57-YKT~LCM6-WCL",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "+1368-05-01",
            julianDateRange: { earliestDay: 2220833, latestDay: 2220833 },
            localizedText: "1 May 1368",
            modifier: null,
            normalizedText: "1 May 1368",
            originalText: "1 May 1368",
          },
          deceasedFlag: null,
          description: null,
          place: {
            geoCode: { latitude: 51.4535, longitude: -0.9784 },
            id: 449383,
            localizedText: "Reading, Berkshire, England, United Kingdom",
            normalizedText: "Reading, Berkshire, England, United Kingdom",
            originalText:
              "Reading Abbey, Queen's Chapel, Reading, Berkshire, England",
          },
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "MYGH-SMM",
      preferred: false,
    },
    "MTWC-ZYV": {
      coupleId: "L8WB-9SV~94K9-WZ4",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "+1408-05-23",
            julianDateRange: { earliestDay: 2235464, latestDay: 2235464 },
            localizedText: "23 May 1408",
            modifier: null,
            normalizedText: "23 May 1408",
            originalText: "23 May 1408",
          },
          deceasedFlag: null,
          description: null,
          place: null,
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "MTWC-ZYV",
      preferred: false,
    },
    "MGQL-BPC": {
      coupleId: "MJ8F-VH3~9791-Z88",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: true,
        researchSuggestionList: null,
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "A+1415",
            julianDateRange: { earliestDay: 2237878, latestDay: 2237878 },
            localizedText: "about 1415",
            modifier: "ABOUT",
            normalizedText: "about 1415",
            originalText: "about 1415",
          },
          deceasedFlag: null,
          description: null,
          place: {
            geoCode: { latitude: 52.8061, longitude: -2.1182 },
            id: 10596212,
            localizedText: "Stafford, Staffordshire, England",
            normalizedText: "Stafford, Staffordshire, England",
            originalText: "Stafford, Staffordshire, England",
          },
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: false,
      id: "MGQL-BPC",
      preferred: false,
      suggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "MGQL-BPC",
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "COUPLE",
              name: "COUPLE_MAY_HAVE_CHILDREN",
            },
          },
        ],
      },
    },
    "M2SJ-XMF": {
      coupleId: "LB5T-GL5~K8RT-425",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "M2SJ-XMF",
            id: null,
            justification: null,
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "COUPLE",
              name: "POSSIBLE_CHILD_GAP_IN_MIDDLE",
            },
          },
        ],
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "A+1358",
            julianDateRange: { earliestDay: 2217060, latestDay: 2217060 },
            localizedText: "about 1358",
            modifier: "ABOUT",
            normalizedText: "about 1358",
            originalText: "about 1358",
          },
          deceasedFlag: null,
          description: null,
          place: {
            geoCode: { latitude: 56.4887, longitude: -3.1028 },
            id: 3427787,
            localizedText: "Fowlis, Perthshire, Scotland",
            normalizedText: "Fowlis, Perthshire, Scotland",
            originalText: "Fowlis, Perthshire, Scotland",
          },
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "M2SJ-XMF",
      preferred: false,
    },
    "MRTL-DFJ": {
      coupleId: "LBXV-7R4~KDQ8-MZ1",
      dismissedSuggestions: {
        dataQualityList: null,
        empty: false,
        researchSuggestionList: [
          {
            category: "RESEARCH_SUGGESTION",
            contextId: null,
            entityId: "MRTL-DFJ",
            id: null,
            justification: null,
            type: {
              canBeDismissed: true,
              category: "RESEARCH_SUGGESTION",
              context: "COUPLE",
              name: "POSSIBLE_CHILD_GAP_IN_MIDDLE",
            },
          },
        ],
      },
      event: {
        contributor: null,
        details: {
          detailsType: "EventDetails",
          date: {
            formalText: "+1369-04-10/",
            julianDateRange: { earliestDay: 2221177, latestDay: 2221177 },
            localizedText: "after 10 April 1369",
            modifier: "AFTER",
            normalizedText: "after 10 April 1369",
            originalText: "after 10 April 1369",
          },
          deceasedFlag: null,
          description: null,
          place: {
            geoCode: { latitude: 50.85, longitude: -0.55 },
            id: 10617779,
            localizedText: "Arundel Castle, Sussex, England",
            normalizedText: "Arundel Castle, Sussex, England",
            originalText: "Arundel Castle, Sussex, England",
          },
          sourceCount: 0,
          title: "",
          type: "MARRIAGE",
        },
        id: null,
        justification: null,
        multiValued: true,
        type: "MARRIAGE",
      },
      hasChildren: true,
      id: "MRTL-DFJ",
      preferred: false,
    },
  },
};
