/* eslint-disable @next/next/no-html-link-for-pages */
import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Podcast Feed Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Podcast Feed Creator <br />
          using <a href="https://www.wikidata.org/">Wikidata</a>
        </h1>

        <p className={styles.description}>
          Get started by using the API{" "}
          {/* <code className={styles.code}>pages/index.tsx</code> */}
        </p>

        <div className={styles.grid}>
          <a href="/api/fetch?id=Q109238858&limit=40" className={styles.card}>
            <h2>Jordan B. Peterson Podcast</h2>
            <p></p>
          </a>
          <a href="/api/fetch?id=Q30323986&limit=40" className={styles.card}>
            <h2>Joe Rogan Experience</h2>
            <p>All old episodes</p>
          </a>
          <a href="/api/fetch?id=Q109248984&limit=40" className={styles.card}>
            <h2>Lex Fridman Podcast</h2>
            <p></p>
          </a>
          <a href="/api/fetch?id=Q2856080&limit=40" className={styles.card}>
            <h2>Radiolab</h2>
            <p></p>
          </a>

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/wikidata_logo.png"
              alt="Wikidata Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
