// import { Box, Container, Heading, SimpleGrid, Text } from "@chakra-ui/react";

import Head from "next/head";
import Link from "next/link";
import type { NextPage } from "next";

export async function getServerSideProps() {
  return {
    redirect: {
      permanent: false,
      destination: "/chart",
    },
    props: {},
  };
}
// const Home: NextPage = () => {
//   return (
//     <Box height="100vh">
//       <Head>
//         <title>Wikidata Charts</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Box as="main" height="100%">
//         <Heading as="h1" p={12} fontSize={64} textAlign="center">
//           Welcome to <Link href="/">Wikidata Charts</Link>
//         </Heading>

//         <Container>
//           <Text as="p" textAlign="center" mb={6}>
//             Get started by visualizing data <code>using charts</code>
//           </Text>

//           <SimpleGrid columns={1} spacing={10}>
//             <Box p={4} border={"1px solid #eaeaea"} style={{ fontSize: "3em" }}>
//               <Link href="/chart">
//                 <a>
//                   <h2>Charts</h2>
//                   <p>Click here to get the charts</p>
//                 </a>
//               </Link>
//             </Box>

//             {/* <Box p={4} border={"1px solid #eaeaea"}>
//               <Link href="/category/podcast">
//                 <a>
//                   <h2>🎙️ Podcasts &rarr;</h2>
//                   <p>Analyze podcast quests and episode frequency</p>
//                 </a>
//               </Link>
//             </Box>
//             <Box p={4} border={"1px solid #eaeaea"}>
//               <Link href="/category/country">
//                 <a>
//                   <h2>🌍 Country &rarr;</h2>
//                   <p>Analyse country indicators such as life expectancy</p>
//                 </a>
//               </Link>
//             </Box>
//             <Box p={4} border={"1px solid #eaeaea"}>
//               <Link href="category/country">
//                 <a>
//                   <h2>🗳️ Election &rarr;</h2>
//                   <p>Analyse candidate data.</p>
//                 </a>
//               </Link>
//             </Box> */}
//             {/*<a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//           }
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           }
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a> */}
//           </SimpleGrid>
//         </Container>
//       </Box>

//       <Box
//         as="footer"
//         position="absolute"
//         width={"100%"}
//         bottom={0}
//         borderTop={"1px solid #eaeaea "}
//       >
//         <Container textAlign="center" p={12}>
//           <a
//             href="https://twitter.com/EntitreeApp"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             Powered by <span>CodeLedge</span>
//           </a>
//         </Container>
//       </Box>
//     </Box>
//   );
// };

// export default Home;
